test: slightly improve the output of the end-to-end tests.

diff --git a/e2e/run_all_tests b/e2e/run_all_tests
--- a/e2e/run_all_tests
+++ b/e2e/run_all_tests
@@ -2,11 +2,14 @@
 set -euo pipefail
 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
 
+# shellcheck source-path=SCRIPTDIR
+source "$SCRIPT_DIR/style.sh"
+
 ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
 FILES="$(find "$SCRIPT_DIR" -name 'test_*' -type f -printf '%P\n' | sort)"
 test_count=0
-test_successes=0
-test_failures=0
+passed_tests=()
+failed_tests=()
 
 if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
   {
@@ -14,6 +17,7 @@ if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
     echo "| ---- | -------- | ------ |"
   } >>"$GITHUB_STEP_SUMMARY"
 fi
+
 for f in $FILES; do
   # split tests into two tranches to reduce test time
   if [ -n "${TEST_TRANCHE_COUNT:-}" ]; then
@@ -23,14 +27,19 @@ for f in $FILES; do
     fi
   fi
   if "$ROOT/e2e/run_test" "$f"; then
-    test_successes=$((test_successes + 1))
+    passed_tests=("${passed_tests[@]}" "$f")
   else
-    test_failures=$((test_failures + 1))
+    failed_tests=("${failed_tests[@]}" "$f")
   fi
-  echo
   test_count=$((test_count + 1))
 done
 
-echo "e2e: $test_count tests passed, $test_successes succeeded, $test_failures failed"
+echo "e2e: ran $test_count tests" >&2
 
-[[ $test_failures = 0 ]]
+if [[ -n "${passed_tests[*]}" ]]; then
+  ok "e2e: ${#passed_tests[*]} tests passed: ${passed_tests[*]}"
+fi
+if [[ -n "${failed_tests[*]}" ]]; then
+  err "e2e: ${#failed_tests[*]} tests failed: ${failed_tests[*]}"
+  exit 1
+fi
diff --git a/e2e/run_test b/e2e/run_test
--- a/e2e/run_test
+++ b/e2e/run_test
@@ -2,6 +2,9 @@
 set -euo pipefail
 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
 
+# shellcheck source-path=SCRIPTDIR
+source "$SCRIPT_DIR/style.sh"
+
 ROOT="$(cd "$SCRIPT_DIR"/.. && pwd)"
 
 TEST="$1"
@@ -9,7 +12,6 @@ TEST_SCRIPT="$SCRIPT_DIR/$TEST"
 
 setup_isolated_env() {
   TEST_ISOLATED_DIR="$(mktemp --tmpdir --directory "$(basename "$TEST").XXXXXX")"
-  echo "Test directory: $TEST_ISOLATED_DIR" >&2
 
   # Use a fake HOME and a fake temporary directory
   TEST_HOME="$TEST_ISOLATED_DIR/home"
@@ -60,32 +62,31 @@ within_isolated_env() {
     MISE_TRUSTED_CONFIG_PATHS="$TEST_HOME" \
     MISE_YES=1 \
     NPM_CONFIG_FUND=false \
+    GITHUB_ACTION="${GITHUB_ACTION:-}" \
     "$@" || return $?
 }
 
 run_test() {
-  echo "::group::E2E $TEST"
-
   setup_isolated_env
   create_isolated_env
 
-  START=$(date +%s)
+  START="$(date +%s)"
   local status=0
   within_isolated_env "$TEST_SCRIPT" || status=$?
-  END=$(date +%s)
+  END="$(date +%s)"
+  echo "$TEST: $((END - START))s" >&2
 
   if [[ "$status" == 0 ]]; then
     remove_isolated_env
     STATUS_MSG=":white_check_mark:"
   else
-    echo "::error file=$TEST::E2E Test Failed (code: $status)"
+    err "E2E Test Failed (code: $status)"
     STATUS_MSG=":x:"
   fi
-  echo "$TEST: $((END - START))s"
   if [[ -n "${GITHUB_STEP_SUMMARY:-}" ]]; then
     echo "| $TEST | $((END - START))s | $STATUS_MSG" >>"$GITHUB_STEP_SUMMARY"
   fi
   return "$status"
 }
 
-run_test
+as_group "E2E $TEST" run_test
