test: simplify E2E asserts

diff --git a/e2e/test_tool_versions_alt b/e2e/test_tool_versions_alt
--- a/e2e/test_tool_versions_alt
+++ b/e2e/test_tool_versions_alt
@@ -1,7 +1,5 @@
 #!/usr/bin/env bash
 
-. ./assert.sh
-
 export RTX_MISSING_RUNTIME_BEHAVIOR=autoinstall
 export RTX_DEFAULT_TOOL_VERSIONS_FILENAME=.alternate-tool-versions
 
@@ -13,6 +11,16 @@ if [[ "$(rtx exec -- shfmt --version)" != "v3.5.0" ]]; then
   exit 1
 fi
 
+assert() {
+  actual="$($1)"
+  actual="${actual%$'\n'}"
+  expected="${2%$'\n'}"
+  if [[ "$actual" != "$expected" ]]; then
+    echo "assertion failed, expected '$expected', got '$actual'"
+    exit 1
+  fi
+}
+
 assert "rtx local" "shfmt 3.5.0"
 
 assert "rtx local -p shfmt@3.6.0" "shfmt 3.6.0"
@@ -23,5 +31,3 @@ if [[ "$(rtx exec -- shfmt --version)" != "v3.6.0" ]]; then
 fi
 
 assert "rtx local shfmt@3.5.0" "shfmt 3.5.0"
-
-assert_end
