test: simplify E2E asserts

diff --git a/e2e/test_env b/e2e/test_env
--- a/e2e/test_env
+++ b/e2e/test_env
@@ -1,9 +1,15 @@
 #!/usr/bin/env bash
 
-. ./assert.sh
+assert() {
+  actual="$($1)"
+  actual="${actual%$'\n'}"
+  expected="${2%$'\n'}"
+  if [[ "$actual" != "$expected" ]]; then
+    echo "assertion failed, expected '$expected', got '$actual'"
+    exit 1
+  fi
+}
 
 rtx i nodejs@16.0.0
 eval "$(rtx env -s bash nodejs@16.0.0)"
 assert "node -v" "v16.0.0"
-
-assert_end
diff --git a/e2e/test_local b/e2e/test_local
--- a/e2e/test_local
+++ b/e2e/test_local
@@ -1,6 +1,20 @@
 #!/usr/bin/env bash
 
-. ./assert.sh
+assert() {
+  actual="$($1)"
+  actual="${actual%$'\n'}"
+  expected="${2%$'\n'}"
+  if [[ "$actual" != "$expected" ]]; then
+    echo "assertion failed, expected '$expected', got '$actual'"
+    exit 1
+  fi
+}
+assert_raises() {
+  if ! $1; then
+    echo "assertion failed: $1"
+    exit 1
+  fi
+}
 
 export RTX_MISSING_RUNTIME_BEHAVIOR=autoinstall
 
@@ -36,5 +50,3 @@ rtx exec -- shfmt --version >&2
 if [[ "$(rtx exec -- shfmt --version)" != "v3.6.0" ]]; then
   exit 1
 fi
-
-assert_end
