Bulk reformat existing scripts

diff --git a/e2e/test_local b/e2e/test_local
--- a/e2e/test_local
+++ b/e2e/test_local
@@ -1,19 +1,19 @@
 #!/usr/bin/env bash
 
 assert() {
-	actual="$($1)"
-	actual="${actual%$'\n'}"
-	expected="${2%$'\n'}"
-	if [[ "$actual" != "$expected" ]]; then
-		echo "assertion failed, expected '$expected', got '$actual'"
-		exit 1
-	fi
+  actual="$($1)"
+  actual="${actual%$'\n'}"
+  expected="${2%$'\n'}"
+  if [[ "$actual" != "$expected" ]]; then
+    echo "assertion failed, expected '$expected', got '$actual'"
+    exit 1
+  fi
 }
 assert_raises() {
-	if ! $1; then
-		echo "assertion failed: $1"
-		exit 1
-	fi
+  if ! $1; then
+    echo "assertion failed: $1"
+    exit 1
+  fi
 }
 
 mise i shfmt@3.6.0 shfmt@3.5.0
@@ -64,7 +64,7 @@ run = 'echo \"testing!\"'
 
 mise exec -- shfmt --version >&2
 if [[ "$(mise exec -- shfmt --version)" != "v3.5.0" ]]; then
-	exit 1
+  exit 1
 fi
 
 mise local shfmt@3.6.0
@@ -92,7 +92,7 @@ run = 'echo \"testing!\"'
 
 mise exec -- shfmt --version >&2
 if [[ "$(mise exec -- shfmt --version)" != "v3.6.0" ]]; then
-	exit 1
+  exit 1
 fi
 
 mise local --rm shfmt
@@ -135,7 +135,7 @@ shfmt      3.5.0 # test comment
 
 mise exec -- shfmt --version >&2
 if [[ "$(mise exec -- shfmt --version)" != "v3.5.0" ]]; then
-	exit 1
+  exit 1
 fi
 
 mise local shfmt@3.6.0
@@ -147,5 +147,5 @@ shfmt      3.6.0 # test comment
 
 mise exec -- shfmt --version >&2
 if [[ "$(mise exec -- shfmt --version)" != "v3.6.0" ]]; then
-	exit 1
+  exit 1
 fi
