test: improve coverage (#444)
* test .node-version parsing

I think this is not always being called due to flaky coverage
on parse_legacy_file. This should always cause that code path
to get hit

* added test for tool_version_list

* wip

* Squashed 'test/data/plugins/tiny/' content from commit 2cd6716

git-subtree-dir: test/data/plugins/tiny
git-subtree-split: 2cd6716c5fbb7bb92c3bd2f681d16aba5141c91e

* added env var to fail tiny list-all in tests

* added test for tiny failure

* added list-legacy-filenames script for tiny

* added test for tiny legacy file

* improve e2e testing

diff --git a/test/data/plugins/tiny/bin/list-all b/test/data/plugins/tiny/bin/list-all
--- a/test/data/plugins/tiny/bin/list-all
+++ b/test/data/plugins/tiny/bin/list-all
@@ -2,6 +2,11 @@
 
 set -eu -o pipefail
 
+if [ "${RTX_TINY_LIST_ALL_FAIL:-}" = "1" ]; then
+  echo "RTX_TINY_LIST_ALL_FAIL is set to 1, failing"
+  exit 1
+fi
+
 echo 1.0.0
 echo 1.1.0
 echo 1.0.1
