fix: preserve npm exit code; exclude workspace-local links from reshim

diff --git a/src/plugins/core/assets/node_npm_shim b/src/plugins/core/assets/node_npm_shim
--- a/src/plugins/core/assets/node_npm_shim
+++ b/src/plugins/core/assets/node_npm_shim
@@ -18,11 +18,17 @@ should_reshim() {
 
   local is_global='' cmd='' cmd_needs_reshim=''
   local additional_bare_cmds=()
+  local has_workspace_flag=false
 
   for arg; do
     case "$arg" in
     -g | --global)
       is_global=true
+      ;;
+
+    --workspace=*)
+      # Workspace-local link: npm link <pkg> --workspace=foo
+      has_workspace_flag=true
       ;;
 
     -*) ;; # Skip other options
@@ -49,8 +55,12 @@ should_reshim() {
     ;;
 
   link | ln)
+    # Workspace-local links are NOT global
+    if [ "$has_workspace_flag" = true ]; then
+      is_global=''
+      cmd_needs_reshim=''
     # Bare link installs a global package
-    if ! [ "${additional_bare_cmds[0]-}" ]; then
+    elif ! [ "${additional_bare_cmds[0]-}" ]; then
       is_global=1
       cmd_needs_reshim=true
     # Links to directories also install a global package
@@ -73,9 +83,13 @@ wrap_npm_if_reshim_is_needed() {
   local npm_cli="$plugin_dir/lib/node_modules/npm/bin/npm-cli.js"
   local node_bin="$plugin_dir/bin/node"
   if should_reshim "$@"; then
+    # Run npm and capture its exit code
     "$node_bin" "$npm_cli" "$@"
+    local npm_exit=$?
     printf "Reshimming mise %s...\n" "$plugin_name" >&2
     mise reshim
+    # Return npm's exit code, not mise reshim's
+    return $npm_exit
   else
     exec "$node_bin" "$npm_cli" "$@"
   fi
